#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
  path: /
  controller: App\Controller\BlogController::index

categorypage:
  path: /category
  controller: App\Controller\CategoryController::index

category_add:
  path: /category/add
  controller: App\Controller\CategoryController::add

category_show:
  path: /category/show/{id}
  controller: App\Controller\CategoryController::show

category_edit:
  path: /category/edit/{id}
  controller: App\Controller\CategoryController::edit
  requirements:
    id: '\d+'

category_remove:
  path: /category/remove/{id}
  controller: App\Controller\CategoryController::remove
  requirements:
    id: '\d+'

articlepage:
  path: /article
  controller: App\Controller\ArticleController::index

article_new:
  path: /article/add
  controller: App\Controller\ArticleController::add

article_show:
  path: /article/show/{id}
  controller: App\Controller\ArticleController::show

article_edit:
  path: /article/edit/{id}
  controller: App\Controller\ArticleController::edit
  requirements:
    id: '\d+'

article_remove:
  path: /article/remove/{id}
  controller: App\Controller\ArticleController::remove
  requirements:
    id: '\d+'